# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metadata.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\037github.com/kashing/goofys/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n\x0cNodeMetadata\x12-\n\x08\x63hildren\x18\x01 \x03(\x0b\x32\x1b.NodeMetadata.ChildrenEntry\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x34\n\x10last_modified_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tdirectory\x18\x05 \x01(\x08\x12\x0c\n\x04root\x18\x06 \x01(\x08\x1a>\n\rChildrenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.NodeMetadata:\x02\x38\x01\x42!Z\x1fgithub.com/kashing/goofys/protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_NODEMETADATA_CHILDRENENTRY = _descriptor.Descriptor(
  name='ChildrenEntry',
  full_name='NodeMetadata.ChildrenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NodeMetadata.ChildrenEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='NodeMetadata.ChildrenEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=292,
)

_NODEMETADATA = _descriptor.Descriptor(
  name='NodeMetadata',
  full_name='NodeMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='children', full_name='NodeMetadata.children', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='NodeMetadata.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_modified_at', full_name='NodeMetadata.last_modified_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeMetadata.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='directory', full_name='NodeMetadata.directory', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root', full_name='NodeMetadata.root', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NODEMETADATA_CHILDRENENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=292,
)

_NODEMETADATA_CHILDRENENTRY.fields_by_name['value'].message_type = _NODEMETADATA
_NODEMETADATA_CHILDRENENTRY.containing_type = _NODEMETADATA
_NODEMETADATA.fields_by_name['children'].message_type = _NODEMETADATA_CHILDRENENTRY
_NODEMETADATA.fields_by_name['last_modified_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['NodeMetadata'] = _NODEMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeMetadata = _reflection.GeneratedProtocolMessageType('NodeMetadata', (_message.Message,), {

  'ChildrenEntry' : _reflection.GeneratedProtocolMessageType('ChildrenEntry', (_message.Message,), {
    'DESCRIPTOR' : _NODEMETADATA_CHILDRENENTRY,
    '__module__' : 'metadata_pb2'
    # @@protoc_insertion_point(class_scope:NodeMetadata.ChildrenEntry)
    })
  ,
  'DESCRIPTOR' : _NODEMETADATA,
  '__module__' : 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:NodeMetadata)
  })
_sym_db.RegisterMessage(NodeMetadata)
_sym_db.RegisterMessage(NodeMetadata.ChildrenEntry)


DESCRIPTOR._options = None
_NODEMETADATA_CHILDRENENTRY._options = None
# @@protoc_insertion_point(module_scope)
